- name: Copy docker-compose file to server
  copy:
    src: "{{ node_file_path }}/docker-compose.yaml"
    dest: "{{ destination_path }}/docker-compose.yaml"

- name: Docker login
  docker_login:
    registery_url: "{{ docker_registry }}"
    username: "{{ docker_username }}"
    password: "{{ docker_password }}"

- name: Start container from compose
  docker-compose:
    project_src: "{{ destination_path }}/docker-compose.yaml"
    state: present